# railway.toml

[phases.setup]
# Install PHP, Node.js, Composer, dan NPM
nixPkgs = ["php", "nodejs", "composer"]

[phases.build]
# Install dependencies Laravel + Node
cmds = [
    "composer install --no-interaction --optimize-autoloader",
    "npm install",
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
# Gunakan PHP built-in server pointing ke folder public
cmd = "php -S 0.0.0.0:$PORT -t public"
